using static FF11stats.Program;

namespace FF11stats
{
    public partial class FormJobPoints : Form
    {
        internal FormJobPoints( Jobs j )
        {
            InitializeComponent();

            const string bu = "物理";
            const string bo = "防御力アップ";
            const string du = "ダメージアップ";
            const string en = "効果時間延長";
            const string ka = "回避アップ";
            const string ko = "攻撃力アップ";
            const string ma = "魔法";
            const string me = "命中アップ";
            const string su = "スキルアップ";
            const string up = "効果アップ";
            ulong jp = 0;

            job = j;
            tableLayoutPanel1.SuspendLayout();
            tableLayoutPanel2.SuspendLayout();
            switch( job ) {
            case Jobs.War:
                jp = cd.JobpoWar;
                Text += "戦士";
                label2.Text = $"マイティストライク{up}";
                label3.Text = $"ブラーゼンラッシュ{up}";
                label4.Text = $"バーサク{up}";
                label5.Text = $"ディフェンダー{up}";
                label6.Text = $"ウォークライ{up}";
                label7.Text = $"アグレッサー{up}";
                label8.Text = $"リタリエーション{up}";
                label9.Text = $"リストレント{up}";
                label10.Text = $"ブラッドレイジ{up}";
                label11.Text = $"ダブルアタック{up}";
                checkBox11.Text = $"フェンサー{up}";
                checkBox14.Text = "クリティカルヒットアップ";
                checkBox15.Text = $"ダブルアタック{up}";
                checkBox17.Text = $"C.インクリース{up}";
                checkBox27.Text = $"フェンサー{up}";
                checkBox29.Text = "ダブルアタック確率アップ";
                checkBox30.Text = $"C.インクリース{up}";
                checkBox33.Text = $"ウェポンスキル{du}";
                checkBox43.Text = $"フェンサー{up}";
                checkBox45.Text = "ダブルアタック確率アップ";
                checkBox46.Text = $"C.インクリース{up}";
                checkBox48.Text = "クリティカルヒットアップ";
                checkBox57.Text = $"フェンサー{up}";
                checkBox58.Text = "ダブルアタック確率アップ";
                checkBox59.Text = $"C.インクリース{up}";
                break;
            case Jobs.Mnk:
                jp = cd.JobpoMnk;
                Text += "モンク";
                label2.Text = $"百裂拳{up}";
                label3.Text = $"インナーストレングス{up}";
                label4.Text = $"回避{up}";
                label5.Text = $"集中{up}";
                label6.Text = $"チャクラ{up}";
                label7.Text = $"かまえる{up}";
                label8.Text = $"猫足立ち{up}";
                label9.Text = $"絶対カウンター{up}";
                label10.Text = $"インピタス{up}";
                label11.Text = $"蹴撃{up}";
                checkBox11.Text = $"ガード{su}";
                checkBox14.Text = $"マーシャルアーツ{up}";
                checkBox15.Text = $"モクシャ{up}";
                checkBox17.Text = $"カウンター{up}";
                checkBox27.Text = $"ガード{su}";
                checkBox29.Text = $"モクシャ{up}";
                checkBox30.Text = $"カウンター{up}";
                checkBox33.Text = $"カウンター{du}";
                checkBox43.Text = $"ガード{su}";
                checkBox45.Text = $"モクシャ{up}";
                checkBox46.Text = $"カウンター{up}";
                checkBox48.Text = $"マーシャルアーツ{up}";
                checkBox57.Text = $"ガード{su}";
                checkBox58.Text = $"モクシャ{up}";
                checkBox59.Text = $"カウンター{up}";
                break;
            case Jobs.Whm:
                jp = cd.JobpoWhm;
                Text += "白魔道士";
                label2.Text = $"女神の祝福{up}";
                label3.Text = $"女神の羽衣{up}";
                label4.Text = $"女神の印{up}";
                label5.Text = "魔法命中アップ";
                label6.Text = $"ハートオブソラス{up}";
                label7.Text = $"ハートオブミゼリ{up}";
                label8.Text = "女神の愛撫時間延長";
                label9.Text = $"女神の聖域{up}";
                label10.Text = $"リジェネ{en}";
                label11.Text = $"属性耐性魔法{up}";
                checkBox1.Text = $"{ma}{bo}";
                checkBox3.Text = $"{ma}{ko}";
                checkBox4.Text = $"{ma}{ka}";
                checkBox6.Text = $"{ma}{me}";
                checkBox7.Text = $"{bu}{me}";
                checkBox10.Text = $"回復魔法{su}";
                checkBox11.Text = $"神聖魔法{su}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = "ケアル回復量アップ";
                checkBox17.Text = "回復魔法詠唱時間短縮";
                checkBox18.Text = $"{ma}{bo}";
                checkBox20.Text = $"{ma}{ko}";
                checkBox21.Text = $"{ma}{ka}";
                checkBox23.Text = $"{ma}{me}";
                checkBox24.Text = $"{bu}{me}";
                checkBox26.Text = $"回復魔法{su}";
                checkBox27.Text = $"神聖魔法{su}";
                checkBox29.Text = "ケアル回復量アップ";
                checkBox30.Text = "回復魔法詠唱時間短縮";
                checkBox33.Text = "リジェネ回復量アップ";
                checkBox34.Text = $"{ma}{bo}";
                checkBox36.Text = $"{ma}{ko}";
                checkBox37.Text = $"{ma}{ka}";
                checkBox39.Text = $"{ma}{me}";
                checkBox40.Text = $"{bu}{me}";
                checkBox42.Text = $"回復魔法{su}";
                checkBox43.Text = $"神聖魔法{su}";
                checkBox45.Text = "ケアル回復量アップ";
                checkBox46.Text = "回復魔法詠唱時間短縮";
                checkBox48.Text = "魔法習得";
                checkBox50.Text = $"{ma}{bo}";
                checkBox52.Text = $"{ma}{ko}";
                checkBox53.Text = $"{ma}{ka}";
                checkBox54.Text = $"{ma}{me}";
                checkBox55.Text = $"{bu}{me}";
                checkBox56.Text = $"回復魔法{su}";
                checkBox57.Text = $"神聖魔法{su}";
                checkBox58.Text = "ケアル回復量アップ";
                checkBox59.Text = "回復魔法詠唱時間短縮";
                break;
            case Jobs.Blm:
                jp = cd.JobpoBlm;
                Text += "黒魔道士";
                label2.Text = $"魔力の泉{up}";
                label3.Text = $"サテルサーサリー{up}";
                label4.Text = $"精霊の印{up}";
                label5.Text = $"マジックバースト{du}";
                label6.Text = $"マナウォール{up}";
                label7.Text = "魔法命中率アップ";
                label8.Text = "エンミティダウス使用間隔短縮";
                label9.Text = $"魔力の雫{up}";
                label10.Text = "マジックバースト敵対心ダウン";
                label11.Text = $"魔法{du}";
                checkBox1.Text = $"{ma}{bo}";
                checkBox3.Text = $"{ma}{ko}";
                checkBox4.Text = $"{ma}{ka}";
                checkBox6.Text = $"{ma}{me}";
                checkBox7.Text = $"精霊魔法{su}";
                checkBox10.Text = $"暗黒魔法{su}";
                checkBox11.Text = $"マジックバースト{du}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = $"魔法{du}";
                checkBox17.Text = $"エレメントセレリティ{up}";
                checkBox18.Text = $"{ma}{bo}";
                checkBox20.Text = $"{ma}{ko}";
                checkBox21.Text = $"{ma}{ka}";
                checkBox23.Text = $"{ma}{me}";
                checkBox24.Text = $"精霊魔法{su}";
                checkBox26.Text = $"暗黒魔法{su}";
                checkBox27.Text = $"マジックバースト{du}";
                checkBox29.Text = $"魔法{du}";
                checkBox30.Text = $"エレメントセレリティ{up}";
                checkBox33.Text = "魔法習得";
                checkBox34.Text = $"{ma}{bo}";
                checkBox36.Text = $"{ma}{ko}";
                checkBox37.Text = $"{ma}{ka}";
                checkBox39.Text = $"{ma}{me}";
                checkBox40.Text = $"精霊魔法{su}";
                checkBox42.Text = $"暗黒魔法{su}";
                checkBox43.Text = $"マジックバースト{du}";
                checkBox45.Text = $"魔法{du}";
                checkBox46.Text = $"エレメントセレリティ{up}";
                checkBox48.Text = "魔法習得";
                checkBox50.Text = $"{ma}{bo}";
                checkBox52.Text = $"{ma}{ko}";
                checkBox53.Text = $"{ma}{ka}";
                checkBox54.Text = $"{ma}{me}";
                checkBox55.Text = $"精霊魔法{su}";
                checkBox56.Text = $"暗黒魔法{su}";
                checkBox57.Text = "MBボーナスアップ";
                checkBox58.Text = $"魔法{du}";
                checkBox59.Text = $"エレメントセレリティ{up}";
                break;
            case Jobs.Rdm:
                jp = cd.JobpoRdm;
                Text += "赤魔道士";
                label2.Text = $"連続魔{up}";
                label3.Text = $"スタイミー{up}";
                label4.Text = $"コンバート{up}";
                label5.Text = $"{ma}{me}";
                label6.Text = $"コンポージャー{up}";
                label7.Text = $"{ma}{ko}";
                label8.Text = $"サボトゥール{up}";
                label9.Text = $"弱体魔法{en}";
                label10.Text = $"クイックマジック{up}";
                label11.Text = $"強化魔法{en}";
                checkBox1.Text = $"{ma}{bo}";
                checkBox3.Text = $"{ma}{ko}";
                checkBox4.Text = $"{ma}{ka}";
                checkBox6.Text = $"{ma}{me}";
                checkBox7.Text = $"{bu}{me}";
                checkBox10.Text = $"弱体魔法{su}";
                checkBox11.Text = $"強化魔法{su}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = $"魔法剣{du}";
                checkBox17.Text = $"ファストキャスト{up}";
                checkBox18.Text = $"{ma}{bo}";
                checkBox20.Text = $"{ma}{ko}";
                checkBox21.Text = $"{ma}{ka}";
                checkBox23.Text = $"{ma}{me}";
                checkBox24.Text = $"{bu}{me}";
                checkBox26.Text = $"弱体魔法{su}";
                checkBox27.Text = $"強化魔法{su}";
                checkBox29.Text = $"魔法剣{du}";
                checkBox30.Text = $"ファストキャスト{up}";
                checkBox33.Text = "魔法習得";
                checkBox34.Text = $"{ma}{bo}";
                checkBox36.Text = $"{ma}{ko}";
                checkBox37.Text = $"{ma}{ka}";
                checkBox39.Text = $"{ma}{me}";
                checkBox40.Text = $"{bu}{me}";
                checkBox42.Text = $"弱体魔法{su}";
                checkBox43.Text = $"強化魔法{su}";
                checkBox45.Text = $"魔法剣{du}";
                checkBox46.Text = $"ファストキャスト{up}";
                checkBox48.Text = "魔法習得";
                checkBox50.Text = $"{ma}{bo}";
                checkBox52.Text = $"{ma}{ko}";
                checkBox53.Text = $"{ma}{ka}";
                checkBox54.Text = $"{ma}{me}";
                checkBox55.Text = $"{bu}{me}";
                checkBox56.Text = $"弱体魔法{su}";
                checkBox57.Text = $"強化魔法{su}";
                checkBox58.Text = $"魔法剣{du}";
                checkBox59.Text = $"ファストキャスト{up}";
                break;
            case Jobs.Thf:
                jp = cd.JobpoThf;
                Text += "シーフ";
                label2.Text = $"絶対回避{up}";
                label3.Text = $"ラーセニー{en}";
                label4.Text = $"不意打ち{up}";
                label5.Text = $"だまし討ち{up}";
                label6.Text = "ぬすむ再使用時間短縮";
                label7.Text = $"かすめとる{up}";
                label8.Text = $"ぶんどる{up}";
                label9.Text = $"コンスピレーター{up}";
                label10.Text = $"まどわす{up}";
                label11.Text = $"トリプルアタック{up}";
                checkBox11.Text = $"トレジャーハンター{up}";
                checkBox14.Text = "トレジャーハンター効果最大値アップ";
                checkBox15.Text = "トリプルアタック確率アップ";
                checkBox17.Text = $"C.インクリース{up}";
                checkBox27.Text = $"トレジャーハンター{up}";
                checkBox29.Text = "トリプルアタック確率アップ";
                checkBox30.Text = $"C.インクリース{up}";
                checkBox33.Text = $"二刀流{up}";
                checkBox43.Text = $"トレジャーハンター{up}";
                checkBox45.Text = "トリプルアタック確率アップ";
                checkBox46.Text = $"C.インクリース{up}";
                checkBox48.Text = "トレジャーハンター効果最大値アップ";
                checkBox57.Text = $"トレジャーハンター{up}";
                checkBox58.Text = "トリプルアタック確率アップ";
                checkBox59.Text = $"C.インクリース{up}";
                break;
            case Jobs.Pld:
                jp = cd.JobpoPld;
                Text += "ナイト";
                label2.Text = $"インビンシブル{up}";
                label3.Text = $"インターヴィーン{up}";
                label4.Text = $"ホーリーサークル{up}";
                label5.Text = $"センチネル{up}";
                label6.Text = $"シールドバッシュ{up}";
                label7.Text = $"かばう{en}";
                label8.Text = $"神聖の印{up}";
                label9.Text = $"セプルカー{en}";
                label10.Text = $"パリセード{up}";
                label11.Text = $"エンライト{up}";
                checkBox11.Text = $"神聖魔法{su}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = $"シールドマスタリー{up}";
                checkBox17.Text = $"C.リデュース{up}";
                checkBox27.Text = $"神聖魔法{su}";
                checkBox29.Text = $"シールドマスタリー{up}";
                checkBox30.Text = $"C.リデュース{up}";
                checkBox33.Text = $"被プロテス{up}";
                checkBox43.Text = $"神聖魔法{su}";
                checkBox45.Text = $"シールドマスタリー{up}";
                checkBox46.Text = $"C.リデュース{up}";
                checkBox48.Text = "ケアル回復量アップ";
                checkBox57.Text = $"神聖魔法{su}";
                checkBox58.Text = $"シールドマスタリー{up}";
                checkBox59.Text = $"C.リデュース{up}";
                break;
            case Jobs.Drk:
                jp = cd.JobpoDrk;
                Text += "暗黒騎士";
                label2.Text = $"ブラッドウェポン{up}";
                label3.Text = $"ソールエンスレーヴ{up}";
                label4.Text = $"アルケインサークル{up}";
                label5.Text = $"ラストリゾート{up}";
                label6.Text = $"暗黒{en}";
                label7.Text = $"ウェポンバッシュ{up}";
                label8.Text = $"ネザーヴォイド{up}";
                label9.Text = $"アルケインクレスト{en}";
                label10.Text = $"レッドデリリアム{en}";
                label11.Text = $"エンダーク{up}";
                checkBox11.Text = $"暗黒魔法{su}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = $"C.インクリース{up}";
                checkBox17.Text = $"ウェポンスキル{du}";
                checkBox27.Text = $"暗黒魔法{su}";
                checkBox29.Text = $"C.インクリース{up}";
                checkBox30.Text = $"ウェポンスキル{du}";
                checkBox33.Text = "魔法習得";
                checkBox43.Text = $"暗黒魔法{su}";
                checkBox45.Text = $"C.インクリース{up}";
                checkBox46.Text = $"ウェポンスキル{du}";
                checkBox48.Text = $"ドレッドスパイク{up}";
                checkBox57.Text = $"暗黒魔法{su}";
                checkBox58.Text = $"C.インクリース{up}";
                checkBox59.Text = $"ウェポンスキル{du}";
                break;
            case Jobs.Bst:
                jp = cd.JobpoBst;
                Text += "獣使い";
                label2.Text = $"使い魔{up}";
                label3.Text = $"アンリーシュ{up}";
                label4.Text = $"ペットの{bu}{me}";
                label5.Text = $"あやつる成功率アップ";
                label6.Text = $"いたわる{up}";
                label7.Text = $"ペット攻撃間隔短縮";
                label8.Text = $"しじをさせろ{up}";
                label9.Text = $"きばれ{up}";
                label10.Text = $"ふりしぼれ{en}";
                label11.Text = $"ペットの{ma}{me}";
                checkBox11.Text = $"ペットの{bu}攻撃力と{bu}{bo}";
                checkBox14.Text = "ほんきだせとしじをさせろ再使用時間短縮";
                checkBox15.Text = $"ペットの{bu}命中と{bu}{ka}";
                checkBox17.Text = $"フェンサー{up}";
                checkBox27.Text = $"ペットの{bu}攻撃力と{bu}{bo}";
                checkBox29.Text = $"ペットの{bu}命中と{bu}{ka}";
                checkBox30.Text = $"フェンサー{up}";
                checkBox33.Text = "ペットのステータスアップ";
                checkBox43.Text = $"ペットの{bu}攻撃力と{bu}{bo}";
                checkBox45.Text = $"ペットの{bu}命中と{bu}{ka}";
                checkBox46.Text = $"フェンサー{up}";
                checkBox48.Text = "ペットのTPボーナスアップ";
                checkBox57.Text = $"ペットの{bu}攻撃力と{bu}{bo}";
                checkBox58.Text = $"ペットの{bu}命中と{bu}{ka}";
                checkBox59.Text = $"フェンサー{up}";
                break;
            case Jobs.Brd:
                jp = cd.JobpoBrd;
                Text += "吟遊詩人";
                label2.Text = $"ソウルボイス{up}";
                label3.Text = $"クラリオンコール{up}";
                label4.Text = $"ミンネ{up}";
                label5.Text = $"メヌエット{up}";
                label6.Text = $"ピアニッシモ{up}";
                label7.Text = "歌の命中率アップ";
                label8.Text = $"テヌート{up}";
                label9.Text = $"ララバイ{en}";
                label10.Text = $"マルカート{up}";
                label11.Text = $"レクイエム{up}";
                checkBox3.Text = $"{bu}{ka}";
                checkBox4.Text = $"{bu}{me}";
                checkBox6.Text = $"{ma}{bo}";
                checkBox11.Text = $"歌唱{su}";
                checkBox14.Text = "歌習得";
                checkBox15.Text = $"弦楽器{su}";
                checkBox17.Text = $"管楽器{su}";
                checkBox20.Text = $"{bu}{ka}";
                checkBox21.Text = $"{bu}{me}";
                checkBox23.Text = $"{ma}{bo}";
                checkBox27.Text = $"歌唱{su}";
                checkBox29.Text = $"弦楽器{su}";
                checkBox30.Text = $"管楽器{su}";
                checkBox33.Text = "歌の詠唱時間短縮";
                checkBox36.Text = $"{bu}{ka}";
                checkBox37.Text = $"{bu}{me}";
                checkBox39.Text = $"{ma}{bo}";
                checkBox43.Text = $"歌唱{su}";
                checkBox45.Text = $"弦楽器{su}";
                checkBox46.Text = $"管楽器{su}";
                checkBox48.Text = $"歌の{en}";
                checkBox52.Text = $"{bu}{ka}";
                checkBox53.Text = $"{bu}{me}";
                checkBox54.Text = $"{ma}{bo}";
                checkBox57.Text = $"歌唱{su}";
                checkBox58.Text = $"弦楽器{su}";
                checkBox59.Text = $"管楽器{su}";
                break;
            case Jobs.Rng:
                jp = cd.JobpoRng;
                Text += "狩人";
                label2.Text = $"イーグルアイ{up}";
                label3.Text = $"オーバーキル{up}";
                label4.Text = $"狙い撃ち{up}";
                label5.Text = $"カモフラージュ{up}";
                label6.Text = $"乱れ撃ち{up}";
                label7.Text = $"影縫い効果{en}";
                label8.Text = $"ベロシティショット{up}";
                label9.Text = $"ダブルショット{up}";
                label10.Text = $"デコイショット{up}";
                label11.Text = $"エンドレスショット{up}";
                checkBox11.Text = $"コンサーブTP{up}";
                checkBox14.Text = $"ベロシティショット{up}";
                checkBox15.Text = $"トゥルーショット{up}";
                checkBox17.Text = $"デッドエイム{up}";
                checkBox27.Text = $"コンサーブTP{up}";
                checkBox29.Text = $"トゥルーショット{up}";
                checkBox30.Text = $"デッドエイム{up}";
                checkBox33.Text = $"乱れ撃ち{up}";
                checkBox43.Text = $"コンサーブTP{up}";
                checkBox45.Text = $"トゥルーショット{up}";
                checkBox46.Text = $"デッドエイム{up}";
                checkBox48.Text = $"ベロシティショット{up}";
                checkBox57.Text = $"コンサーブTP{up}";
                checkBox58.Text = $"トゥルーショット{up}";
                checkBox59.Text = $"デッドエイム{up}";
                break;
            case Jobs.Sam:
                jp = cd.JobpoSam;
                Text += "侍";
                label2.Text = $"明鏡止水{up}";
                label3.Text = $"八重霞{up}";
                label4.Text = $"護摩の守護円{up}";
                label5.Text = $"八双{up}";
                label6.Text = $"黙想{up}";
                label7.Text = $"星眼{up}";
                label8.Text = $"渾然一体{up}";
                label9.Text = $"破魔の刃{en}";
                label10.Text = $"葉隠{up}";
                label11.Text = $"残心{up}";
                checkBox1.Text = "-";
                checkBox11.Text = $"残心{up}";
                checkBox14.Text = $"八双、星眼{up}";
                checkBox15.Text = $"ストアTP{up}";
                checkBox17.Text = $"連携ボーナス{up}";
                checkBox27.Text = "残心確率アップ";
                checkBox29.Text = $"ストアTP{up}";
                checkBox30.Text = $"連携ボーナス{up}";
                checkBox33.Text = $"心眼{up}";
                checkBox43.Text = $"残心{up}";
                checkBox45.Text = $"ストアTP{up}";
                checkBox46.Text = $"連携ボーナス{up}";
                checkBox48.Text = $"八双と星眼{up}";
                checkBox57.Text = $"残心確率アップ";
                checkBox58.Text = $"ストアTP{up}";
                checkBox59.Text = $"連携ボーナス{up}";
                break;
            case Jobs.Nin:
                jp = cd.JobpoNin;
                Text += "忍者";
                label2.Text = $"微塵がくれ{up}";
                label3.Text = $"身影{up}";
                label4.Text = $"陽忍{up}";
                label5.Text = $"陰忍{up}";
                label6.Text = $"忍術{me}";
                label7.Text = "忍術の詠唱時間短縮";
                label8.Text = $"二重{up}";
                label9.Text = $"遁術{up}";
                label10.Text = $"一隻眼{up}";
                label11.Text = $"タクティカルパリー{up}";
                checkBox7.Text = $"{ma}{ko}";
                checkBox10.Text = $"{ma}{ka}";
                checkBox11.Text = $"{ma}{me}";
                checkBox14.Text = "忍術習得";
                checkBox15.Text = $"忍術{su}";
                checkBox17.Text = $"打剣{up}";
                checkBox24.Text = $"{ma}{ko}";
                checkBox26.Text = $"{ma}{ka}";
                checkBox27.Text = $"{ma}{me}";
                checkBox29.Text = $"忍術{su}";
                checkBox30.Text = $"打剣{up}";
                checkBox33.Text = $"忍術{en}";
                checkBox40.Text = $"{ma}{ko}";
                checkBox42.Text = $"{ma}{ka}";
                checkBox43.Text = $"{ma}{me}";
                checkBox45.Text = $"忍術{su}";
                checkBox46.Text = $"打剣{up}";
                checkBox48.Text = $"ウェポンスキル{du}";
                checkBox55.Text = $"{ma}{ko}";
                checkBox56.Text = $"{ma}{ka}";
                checkBox57.Text = $"{ma}{me}";
                checkBox58.Text = $"忍術{su}";
                checkBox59.Text = $"打剣{up}";
                break;
            case Jobs.Drg:
                jp = cd.JobpoDrg;
                Text += "竜騎士";
                label2.Text = $"竜剣{up}";
                label3.Text = $"フライハイ{up}";
                label4.Text = $"エンシェントサークル{up}";
                label5.Text = $"ジャンプ{up}";
                label6.Text = $"スピリットリンク{up}";
                label7.Text = "ワイバーンの最大HPアップ";
                label8.Text = $"ドラゴンブレイカー{en}";
                label9.Text = $"ワイバーンのブレス{up}";
                label10.Text = $"ハイジャンプ{up}";
                label11.Text = $"ワイバーンSTアップ時の{up}";
                checkBox11.Text = $"クリティカル{du}";
                checkBox14.Text = $"ワイバーンステータスアップ時の{up}";
                checkBox15.Text = $"ワイバーンの{bu}命中、{bu}{ka}";
                checkBox17.Text = $"ワイバーンの{ma}命中、{ma}{ka}";
                checkBox27.Text = $"クリティカル{du}";
                checkBox29.Text = $"ワイバーンの{bu}命中、{bu}{ka}";
                checkBox30.Text = $"ワイバーンの{ma}命中、{ma}{ka}";
                checkBox33.Text = "レストア/スマイトブレスの再使用時間短縮";
                checkBox43.Text = $"クリティカル{du}";
                checkBox45.Text = $"ワイバーンの{bu}命中と{bu}{ka}";
                checkBox46.Text = $"ワイバーンの{ma}命中と{ma}{ka}";
                checkBox48.Text = $"ワイバーンステータスアップ時の{up}";
                checkBox57.Text = $"クリティカル{du}";
                checkBox58.Text = $"ワイバーンの{bu}命中と{bu}{ka}";
                checkBox59.Text = $"ワイバーンの{ma}命中と{ma}{ka}";
                break;
            case Jobs.Smn:
                jp = cd.JobpoSmn;
                Text += "召喚士";
                label2.Text = $"アストラルフロウ{up}";
                label3.Text = $"アストラルパッセージ{up}";
                label4.Text = $"召喚獣と精霊の{bu}{me}";
                label5.Text = $"召喚獣と精霊の{ma}{me}";
                label6.Text = $"エレメントサイフォン{up}";
                label7.Text = $"召喚獣と精霊の{bu}{ko}";
                label8.Text = $"マナシード{up}";
                label9.Text = $"神獣の加護{up}";
                label10.Text = $"神獣と精霊の{ma}{du}";
                label11.Text = $"契約の履行{du}";
                checkBox1.Text = $"{ma}{bo}";
                checkBox3.Text = $"{ma}{ka}";
                checkBox4.Text = $"{bu}{bo}";
                checkBox6.Text = $"{bu}{ka}";
                checkBox7.Text = $"精霊、召喚獣の{bu}攻撃力、{bu}{bo}";
                checkBox10.Text = $"精霊、召喚獣の{bu}命中、{bu}{ka}";
                checkBox11.Text = $"精霊、召喚獣の{ma}攻撃力、{ma}{bo}";
                checkBox14.Text = "契約の履行の再使用時間短縮";
                checkBox15.Text = $"精霊、神獣の{ma}命中、{ma}{ka}";
                checkBox17.Text = $"召喚魔法{su}";
                checkBox18.Text = $"{ma}{bo}";
                checkBox20.Text = $"{ma}{ka}";
                checkBox21.Text = $"{bu}{bo}";
                checkBox23.Text = $"{bu}{ka}";
                checkBox24.Text = $"神獣、精霊の{bu}攻撃力、{bu}{bo}";
                checkBox26.Text = $"神獣、精霊の{bu}命中、{bu}{ka}";
                checkBox27.Text = $"神獣、精霊の{ma}攻撃力、{ma}{bo}";
                checkBox29.Text = $"神獣、精霊の{ma}命中、{ma}{ka}";
                checkBox30.Text = $"召喚魔法{su}";
                checkBox33.Text = $"神獣の加護{up}";
                checkBox34.Text = $"{ma}{bo}";
                checkBox36.Text = $"{ma}{ka}";
                checkBox37.Text = $"{bu}{bo}";
                checkBox39.Text = $"{bu}{ka}";
                checkBox40.Text = $"精霊と召喚獣の{bu}攻撃力と{bu}{bo}";
                checkBox42.Text = $"精霊と召喚獣の{bu}命中と{bu}{ka}";
                checkBox43.Text = $"精霊と召喚獣の{ma}攻撃力と{ma}{bo}";
                checkBox45.Text = $"精霊と神獣の{ma}命中と{ma}{ka}";
                checkBox46.Text = $"召喚魔法{su}";
                checkBox48.Text = "契約の履行の再使用時間短縮";
                checkBox50.Text = $"{ma}{bo}";
                checkBox52.Text = $"{ma}{ka}";
                checkBox53.Text = $"{bu}{bo}";
                checkBox54.Text = $"{bu}{ka}";
                checkBox55.Text = $"神獣と精霊の{bu}攻撃力と{bu}{bo}";
                checkBox56.Text = $"神獣と精霊の{bu}命中と{bu}{ka}";
                checkBox57.Text = $"神獣と精霊の{ma}攻撃力と{ma}{bo}";
                checkBox58.Text = $"神獣と精霊の{ma}命中と{ma}{ka}";
                checkBox59.Text = $"召喚魔法{su}";
                break;
            case Jobs.Blu:
                jp = cd.JobpoBlu;
                Text += "青魔道士";
                label2.Text = $"アジュールロー{up}";
                label3.Text = $"N.ウィズドム{up}";
                label4.Text = "青魔法ポイントアップ";
                label5.Text = $"ブルーバースト{up}";
                label6.Text = $"ブルーチェーン{up}";
                label7.Text = $"{bu}系青魔法追加効果{me}";
                label8.Text = $"ノートリアスナレッジ{up}";
                label9.Text = $"ノートリアスナレッジ{up}II";
                label10.Text = $"エフラックス{up}";
                label11.Text = $"{ma}{me}";
                checkBox7.Text = $"{ma}{bo}";
                checkBox10.Text = $"{ma}{ko}";
                checkBox11.Text = $"{ma}{ka}";
                checkBox14.Text = $"ジョブ特性{up}";
                checkBox15.Text = $"{ma}{me}";
                checkBox17.Text = $"青魔法{su}";
                checkBox24.Text = $"{ma}{bo}";
                checkBox26.Text = $"{ma}{ko}";
                checkBox27.Text = $"{ma}{ka}";
                checkBox29.Text = $"{ma}{me}";
                checkBox30.Text = $"青魔法{su}";
                checkBox33.Text = $"青魔法{up}";
                checkBox40.Text = $"{ma}{bo}";
                checkBox42.Text = $"{ma}{ko}";
                checkBox43.Text = $"{ma}{ka}";
                checkBox45.Text = $"{ma}{me}";
                checkBox46.Text = $"青魔法{su}";
                checkBox48.Text = $"ジョブ特性{up}";
                checkBox55.Text = $"{ma}{bo}";
                checkBox56.Text = $"{ma}{ko}";
                checkBox57.Text = $"{ma}{ka}";
                checkBox58.Text = $"{ma}{me}";
                checkBox59.Text = $"青魔法{su}";
                break;
            case Jobs.Cor:
                jp = cd.JobpoCor;
                Text += "コルセア";
                label2.Text = $"ワイルドカード{up}";
                label3.Text = $"カットカード{up}";
                label4.Text = $"ファントムロール{en}";
                label5.Text = "Bust回避";
                label6.Text = $"クイックドロー{up}";
                label7.Text = "矢弾消費量軽減";
                label8.Text = $"ランダムディール{up}";
                label9.Text = $"遠隔{me}";
                label10.Text = $"トリプルショット{up}";
                label11.Text = $"適正距離の遠隔{ko}";
                checkBox7.Text = $"{ma}{ko}";
                checkBox10.Text = $"{ma}{ka}";
                checkBox11.Text = $"{ma}{me}";
                checkBox14.Text = $"スナップショット{up}";
                checkBox15.Text = "矢弾消費量軽減";
                checkBox17.Text = $"トゥルーショット{up}";
                checkBox24.Text = $"{ma}{ko}";
                checkBox26.Text = $"{ma}{ka}";
                checkBox27.Text = $"{ma}{me}";
                checkBox29.Text = "矢弾消費量軽減";
                checkBox30.Text = $"トゥルーショット{up}";
                checkBox33.Text = "クイックドロー再使用時間短縮";
                checkBox40.Text = $"{ma}{ko}";
                checkBox42.Text = $"{ma}{ka}";
                checkBox43.Text = $"{ma}{me}";
                checkBox45.Text = "矢弾消費量軽減";
                checkBox46.Text = $"トゥルーショット{up}";
                checkBox48.Text = $"スナップショット{up}";
                checkBox55.Text = $"{ma}{ko}";
                checkBox56.Text = $"{ma}{ka}";
                checkBox57.Text = $"{ma}{me}";
                checkBox58.Text = "矢弾消費量軽減";
                checkBox59.Text = $"トゥルーショット{up}";
                break;
            case Jobs.Pup:
                jp = cd.JobpoPup;
                Text += "からくり士";
                label2.Text = $"オーバードライヴ{up}";
                label3.Text = $"ヘディーアーテフィス{up}";
                label4.Text = "オートマトン最大HP、最大MPアップ";
                label5.Text = $"アクティベート{up}";
                label6.Text = $"リペアー{up}";
                label7.Text = "応急処置再使用時間短縮";
                label8.Text = $"タクティクスウィッチ{up}";
                label9.Text = $"クールダウン{up}";
                label10.Text = $"ディアクティベート{up}";
                label11.Text = $"マーシャルアーツ{up}";
                checkBox1.Text = $"{bu}{ko}";
                checkBox3.Text = $"{bu}{ka}";
                checkBox4.Text = $"{bu}{me}";
                checkBox6.Text = $"{ma}{ka}";
                checkBox7.Text = $"{ma}{me}";
                checkBox10.Text = $"オートマトンの{bu}攻撃力と{bu}{bo}";
                checkBox11.Text = $"オートマトンの{bu}命中と{bu}{ka}";
                checkBox14.Text = "オートマトン属性値アップ";
                checkBox15.Text = $"オートマトンの{ma}攻撃力と{ma}{bo}";
                checkBox17.Text = $"オートマトンの{ma}命中と{ma}{ka}";
                checkBox18.Text = $"{bu}{ko}";
                checkBox20.Text = $"{bu}{ka}";
                checkBox21.Text = $"{bu}{me}";
                checkBox23.Text = $"{ma}{ka}";
                checkBox24.Text = $"{ma}{me}";
                checkBox26.Text = $"オートマトンの{bu}攻撃力と{bu}{bo}";
                checkBox27.Text = $"オートマトンの{bu}命中と{bu}{ka}";
                checkBox29.Text = $"オートマトンの{ma}攻撃力と{ma}{bo}";
                checkBox30.Text = $"オートマトンの{ma}命中と{ma}{ka}";
                checkBox33.Text = $"マーシャルアーツ{up}";
                checkBox34.Text = $"{bu}{ko}";
                checkBox36.Text = $"{bu}{ka}";
                checkBox37.Text = $"{bu}{me}";
                checkBox39.Text = $"{ma}{ka}";
                checkBox40.Text = $"{ma}{me}";
                checkBox42.Text = $"オートマトンの{bu}攻撃力と{bu}{bo}";
                checkBox43.Text = $"オートマトンの{bu}命中と{bu}{ka}";
                checkBox45.Text = $"オートマトンの{ma}攻撃力と{ma}{bo}";
                checkBox46.Text = $"オートマトンの{ma}命中と{ma}{ka}";
                checkBox48.Text = "オートマトンの属性値アップ";
                checkBox50.Text = $"{bu}{ko}";
                checkBox52.Text = $"{bu}{ka}";
                checkBox53.Text = $"{bu}{me}";
                checkBox54.Text = $"{ma}{ka}";
                checkBox55.Text = $"{ma}{me}";
                checkBox56.Text = $"オートマトンの{bu}攻撃力と{bu}{bo}";
                checkBox57.Text = $"オートマトンの{bu}命中と{bu}{ka}";
                checkBox58.Text = $"オートマトンの{ma}攻撃力と{ma}{bo}";
                checkBox59.Text = $"オートマトンの{ma}命中と{ma}{ka}";
                break;
            case Jobs.Dnc:
                jp = cd.JobpoDnc;
                Text += "踊り子";
                label2.Text = $"トランス{up}";
                label3.Text = $"グランドパー{up}";
                label4.Text = $"ステップ{en}";
                label5.Text = $"サンバ{en}";
                label6.Text = "ワルツ回復量アップ";
                label7.Text = $"ジグ{en}";
                label8.Text = $"フラリッシュI{up}";
                label9.Text = $"フラリッシュII{up}";
                label10.Text = $"フラリッシュIII{up}";
                label11.Text = $"コントラダンス{up}";
                checkBox11.Text = $"モクシャ{up}";
                checkBox14.Text = "フィニシングムーブ最大値アップ";
                checkBox15.Text = $"C.インクリース{up}";
                checkBox17.Text = $"連携ボーナス{up}";
                checkBox27.Text = $"モクシャ{up}";
                checkBox29.Text = $"C.インクリース{up}";
                checkBox30.Text = $"連携ボーナス{up}";
                checkBox33.Text = $"二刀流{up}";
                checkBox43.Text = $"モクシャ{up}";
                checkBox45.Text = $"C.インクリース{up}";
                checkBox46.Text = $"連携ボーナス{up}";
                checkBox48.Text = "フィニシングムーブ最大値アップ";
                checkBox57.Text = $"モクシャ{up}";
                checkBox58.Text = $"C.インクリース{up}";
                checkBox59.Text = $"連携ボーナス{up}";
                break;
            case Jobs.Sch:
                jp = cd.JobpoSch;
                Text += "学者";
                label2.Text = $"連環計{up}";
                label3.Text = $"カペルエミサリウス{up}";
                label4.Text = $"白のグリモア{up}";
                label5.Text = $"黒のグリモア{up}";
                label6.Text = $"戦術魔道書{up}I";
                label7.Text = $"戦術魔道書{up}II";
                label8.Text = $"戦術魔道書{up}III";
                label9.Text = $"戦術魔道書{up}IV";
                label10.Text = $"以逸待労の計{up}";
                label11.Text = $"机上演習{up}";
                checkBox1.Text = $"{ma}{bo}";
                checkBox3.Text = $"{ma}{ko}";
                checkBox4.Text = $"{ma}{ka}";
                checkBox6.Text = $"{ma}{me}";
                checkBox7.Text = $"暗黒魔法{su}";
                checkBox10.Text = $"強化魔法{su}";
                checkBox11.Text = $"精霊魔法{su}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = $"回復魔法{su}";
                checkBox17.Text = $"マジックバースト{du}";
                checkBox18.Text = $"{ma}{bo}";
                checkBox20.Text = $"{ma}{ko}";
                checkBox21.Text = $"{ma}{ka}";
                checkBox23.Text = $"{ma}{me}";
                checkBox24.Text = $"暗黒魔法{su}";
                checkBox26.Text = $"強化魔法{su}";
                checkBox27.Text = $"精霊魔法{su}";
                checkBox29.Text = $"回復魔法{su}";
                checkBox30.Text = $"マジックバースト{du}";
                checkBox33.Text = "戦術魔道書再使用時間短縮";
                checkBox34.Text = $"{ma}{bo}";
                checkBox36.Text = $"{ma}{ko}";
                checkBox37.Text = $"{ma}{ka}";
                checkBox39.Text = $"{ma}{me}";
                checkBox40.Text = $"暗黒魔法{su}";
                checkBox42.Text = $"強化魔法{su}";
                checkBox43.Text = $"精霊魔法{su}";
                checkBox45.Text = $"回復魔法{su}";
                checkBox46.Text = $"マジックバースト{du}";
                checkBox48.Text = "魔法習得";
                checkBox50.Text = $"{ma}{bo}";
                checkBox52.Text = $"{ma}{ko}";
                checkBox53.Text = $"{ma}{ka}";
                checkBox54.Text = $"{ma}{me}";
                checkBox55.Text = $"暗黒魔法{su}";
                checkBox56.Text = $"強化魔法{su}";
                checkBox57.Text = $"精霊魔法{su}";
                checkBox58.Text = $"回復魔法{su}";
                checkBox59.Text = $"マジックバースト{du}";
                break;
            case Jobs.Geo:
                jp = cd.JobpoGeo;
                Text += "風水士";
                label2.Text = $"ボルスター{up}";
                label3.Text = $"ワイデンコンパス{up}";
                label4.Text = $"ライフサイクル{up}";
                label5.Text = $"グローリーブレイズ{up}";
                label6.Text = $"{ma}{ko}";
                label7.Text = $"{ma}命中率アップ";
                label8.Text = $"デマテリアライズ{en}";
                label9.Text = $"タウマテルギフォカス{up}";
                label10.Text = $"コンセントリクパルス{up}";
                label11.Text = $"インデ系{ma}{en}";
                checkBox1.Text = $"{ma}{bo}";
                checkBox3.Text = $"{ma}{ko}";
                checkBox4.Text = $"{ma}{ka}";
                checkBox6.Text = $"{ma}{me}";
                checkBox7.Text = $"風水魔法{su}";
                checkBox10.Text = $"風水鈴{su}";
                checkBox11.Text = $"精霊魔法{su}";
                checkBox14.Text = "魔法習得";
                checkBox15.Text = $"暗黒魔法{su}";
                checkBox17.Text = $"{ma}{du}";
                checkBox18.Text = $"{ma}{bo}";
                checkBox20.Text = $"{ma}{ko}";
                checkBox21.Text = $"{ma}{ka}";
                checkBox23.Text = $"{ma}{me}";
                checkBox24.Text = $"風水魔法{su}";
                checkBox26.Text = $"風水鈴{su}";
                checkBox27.Text = $"精霊魔法{su}";
                checkBox29.Text = $"暗黒魔法{su}";
                checkBox30.Text = $"{ma}{du}";
                checkBox33.Text = "魔法習得";
                checkBox34.Text = $"{ma}{bo}";
                checkBox36.Text = $"{ma}{ko}";
                checkBox37.Text = $"{ma}{ka}";
                checkBox39.Text = $"{ma}{me}";
                checkBox40.Text = $"風水魔法{su}";
                checkBox42.Text = $"風水鈴{su}";
                checkBox43.Text = $"精霊魔法{su}";
                checkBox45.Text = $"暗黒魔法{su}";
                checkBox46.Text = $"{ma}{du}";
                checkBox48.Text = "魔法習得";
                checkBox50.Text = $"{ma}{bo}";
                checkBox52.Text = $"{ma}{ko}";
                checkBox53.Text = $"{ma}{ka}";
                checkBox54.Text = $"{ma}{me}";
                checkBox55.Text = $"風水魔法{su}";
                checkBox56.Text = $"風水鈴{su}";
                checkBox57.Text = $"精霊魔法{su}";
                checkBox58.Text = $"暗黒魔法{su}";
                checkBox59.Text = $"{ma}{du}";
                break;
            case Jobs.Run:
                jp = cd.JobpoRun;
                Text += "魔導剣士";
                label2.Text = $"E.スフォルツォ{up}";
                label3.Text = $"オディリックサブタ{up}";
                label4.Text = $"エンチャントルーン{up}";
                label5.Text = $"ヴァレション{en}";
                label6.Text = $"ソードプレイ{up}";
                label7.Text = $"スワイプ{up}";
                label8.Text = $"エンボルド{up}";
                label9.Text = $"ビベイシャス{up}";
                label10.Text = $"ワンフォアオール{en}";
                label11.Text = $"ガンビット{en}";
                checkBox7.Text = $"{ma}{bo}";
                checkBox10.Text = $"{ma}{ka}";
                checkBox11.Text = $"{ma}{me}";
                checkBox14.Text = $"被強化魔法{en}";
                checkBox15.Text = $"強化魔法{su}";
                checkBox17.Text = $"インクァルタタ{up}";
                checkBox24.Text = $"{ma}{bo}";
                checkBox26.Text = $"{ma}{ka}";
                checkBox27.Text = $"{ma}{me}";
                checkBox29.Text = $"強化魔法{su}";
                checkBox30.Text = $"インクァルタタ{up}";
                checkBox33.Text = "魔法習得";
                checkBox40.Text = $"{ma}{bo}";
                checkBox42.Text = $"{ma}{ka}";
                checkBox43.Text = $"{ma}{me}";
                checkBox45.Text = $"強化魔法{su}";
                checkBox46.Text = $"インクァルタタ{up}";
                checkBox48.Text = $"被強化魔法{en}";
                checkBox55.Text = $"{ma}{bo}";
                checkBox56.Text = $"{ma}{ka}";
                checkBox57.Text = $"{ma}{me}";
                checkBox58.Text = $"強化魔法{su}";
                checkBox59.Text = $"インクァルタタ{up}";
                break;
            }
            numericUpDown1.Value = jp & 0x1F;
            numericUpDown2.Value = ( jp & 0x0000_0000_0000_03E0ul ) >>> 5;
            numericUpDown3.Value = ( jp & 0x0000_0000_0000_7C00ul ) >>> 10;
            numericUpDown4.Value = ( jp & 0x0000_0000_000F_8000ul ) >>> 15;
            numericUpDown5.Value = ( jp & 0x0000_0000_01F0_0000ul ) >>> 20;
            numericUpDown6.Value = ( jp & 0x0000_0000_3E00_0000ul ) >>> 25;
            numericUpDown7.Value = ( jp & 0x0000_0007_C000_0000ul ) >>> 30;
            numericUpDown8.Value = ( jp & 0x0000_00F8_0000_0000ul ) >>> 35;
            numericUpDown9.Value = ( jp & 0x0000_1F00_0000_0000ul ) >>> 40;
            numericUpDown10.Value = ( jp & 0x0003_E000_0000_0000ul ) >>> 45;
            foreach( Control c in tableLayoutPanel1.Controls ) {
                if( c is Label l ) {
                    l.Anchor = AnchorStyles.Left;
                }
            }
            foreach( Control c in tableLayoutPanel2.Controls ) {
                if( c is CheckBox cb ) {
                    cb.AutoCheck = false;
                    cb.TabStop = false;
                } else if( c is Label l ) {
                    l.Anchor = AnchorStyles.Right;
                }
            }
            label12.Anchor = AnchorStyles.Left;
            tableLayoutPanel1.ResumeLayout();
            tableLayoutPanel2.ResumeLayout();
        }

        static Jobs job;

        private void Button1_Click( object sender, EventArgs e )
        {
            foreach( Control c in tableLayoutPanel1.Controls ) {
                if( c is NumericUpDown n ) {
                    n.Value = n.Maximum;
                }
            }
            return;
        }

        private void Button2_Click( object sender, EventArgs e )
        {
            foreach( Control c in tableLayoutPanel1.Controls ) {
                if( c is NumericUpDown n ) {
                    n.Value = 0;
                }
            }
            return;
        }

        private void Button3_Click( object sender, EventArgs e )
        {
            ulong u = (ulong)numericUpDown10.Value << 45 | (ulong)numericUpDown9.Value << 40 | (ulong)numericUpDown8.Value << 35 | (ulong)numericUpDown7.Value << 30 | (ulong)numericUpDown6.Value << 25
                    | (ulong)numericUpDown5.Value << 20 | (ulong)numericUpDown4.Value << 15 | (ulong)numericUpDown3.Value << 10 | (ulong)numericUpDown2.Value << 5 | (ulong)numericUpDown1.Value;

            switch( job ) {
            case Jobs.War:
                cd.JobpoWar = u;
                break;
            case Jobs.Mnk:
                cd.JobpoMnk = u;
                break;
            case Jobs.Whm:
                cd.JobpoWhm = u;
                break;
            case Jobs.Blm:
                cd.JobpoBlm = u;
                break;
            case Jobs.Rdm:
                cd.JobpoRdm = u;
                break;
            case Jobs.Thf:
                cd.JobpoThf = u;
                break;
            case Jobs.Pld:
                cd.JobpoPld = u;
                break;
            case Jobs.Drk:
                cd.JobpoDrk = u;
                break;
            case Jobs.Bst:
                cd.JobpoBst = u;
                break;
            case Jobs.Brd:
                cd.JobpoBrd = u;
                break;
            case Jobs.Rng:
                cd.JobpoRng = u;
                break;
            case Jobs.Sam:
                cd.JobpoSam = u;
                break;
            case Jobs.Nin:
                cd.JobpoNin = u;
                break;
            case Jobs.Drg:
                cd.JobpoDrg = u;
                break;
            case Jobs.Smn:
                cd.JobpoSmn = u;
                break;
            case Jobs.Blu:
                cd.JobpoBlu = u;
                break;
            case Jobs.Cor:
                cd.JobpoCor = u;
                break;
            case Jobs.Pup:
                cd.JobpoPup = u;
                break;
            case Jobs.Dnc:
                cd.JobpoDnc = u;
                break;
            case Jobs.Sch:
                cd.JobpoSch = u;
                break;
            case Jobs.Geo:
                cd.JobpoGeo = u;
                break;
            case Jobs.Run:
                cd.JobpoRun = u;
                break;
            }
            Close();
            return;
        }

        private void Button4_Click( object sender, EventArgs e )
        {
            Close();
            return;
        }

        private void NumericUpDown1_ValueChanged( object sender, EventArgs e )
        {
            decimal gift = 0;

            foreach( Control c in tableLayoutPanel1.Controls ) {
                if( c is NumericUpDown n ) {
                    gift += n.Value * ( n.Value + 1 ) / 2;
                }
            }
            label14.Text = $"{gift}";
            progressBar1.Value = (int)gift;
            checkBox1.Checked = decimal.Parse( label15.Text ) <= gift;
            checkBox2.Checked = decimal.Parse( label16.Text ) <= gift;
            checkBox3.Checked = decimal.Parse( label17.Text ) <= gift;
            checkBox4.Checked = decimal.Parse( label18.Text ) <= gift;
            checkBox5.Checked = decimal.Parse( label19.Text ) <= gift;
            checkBox6.Checked = decimal.Parse( label20.Text ) <= gift;
            checkBox7.Checked = decimal.Parse( label21.Text ) <= gift;
            checkBox8.Checked = decimal.Parse( label22.Text ) <= gift;
            checkBox9.Checked = decimal.Parse( label23.Text ) <= gift;
            checkBox10.Checked = decimal.Parse( label24.Text ) <= gift;
            checkBox11.Checked = decimal.Parse( label25.Text ) <= gift;
            checkBox12.Checked = decimal.Parse( label26.Text ) <= gift;
            checkBox13.Checked = decimal.Parse( label27.Text ) <= gift;
            checkBox14.Checked = decimal.Parse( label28.Text ) <= gift;
            checkBox15.Checked = decimal.Parse( label29.Text ) <= gift;
            checkBox16.Checked = decimal.Parse( label30.Text ) <= gift;
            checkBox17.Checked = decimal.Parse( label31.Text ) <= gift;
            checkBox18.Checked = decimal.Parse( label32.Text ) <= gift;
            checkBox19.Checked = decimal.Parse( label33.Text ) <= gift;
            checkBox20.Checked = decimal.Parse( label34.Text ) <= gift;
            checkBox21.Checked = decimal.Parse( label35.Text ) <= gift;
            checkBox22.Checked = decimal.Parse( label36.Text ) <= gift;
            checkBox23.Checked = decimal.Parse( label37.Text ) <= gift;
            checkBox24.Checked = decimal.Parse( label38.Text ) <= gift;
            checkBox25.Checked = decimal.Parse( label39.Text ) <= gift;
            checkBox26.Checked = decimal.Parse( label40.Text ) <= gift;
            checkBox27.Checked = decimal.Parse( label41.Text ) <= gift;
            checkBox28.Checked = decimal.Parse( label42.Text ) <= gift;
            checkBox29.Checked = decimal.Parse( label43.Text ) <= gift;
            checkBox30.Checked = decimal.Parse( label44.Text ) <= gift;
            checkBox31.Checked = decimal.Parse( label45.Text ) <= gift;
            checkBox32.Checked = decimal.Parse( label46.Text ) <= gift;
            checkBox33.Checked = decimal.Parse( label47.Text ) <= gift;
            checkBox34.Checked = decimal.Parse( label48.Text ) <= gift;
            checkBox35.Checked = decimal.Parse( label49.Text ) <= gift;
            checkBox36.Checked = decimal.Parse( label50.Text ) <= gift;
            checkBox37.Checked = decimal.Parse( label51.Text ) <= gift;
            checkBox38.Checked = decimal.Parse( label52.Text ) <= gift;
            checkBox39.Checked = decimal.Parse( label53.Text ) <= gift;
            checkBox40.Checked = decimal.Parse( label54.Text ) <= gift;
            checkBox41.Checked = decimal.Parse( label55.Text ) <= gift;
            checkBox42.Checked = decimal.Parse( label56.Text ) <= gift;
            checkBox43.Checked = decimal.Parse( label57.Text ) <= gift;
            checkBox44.Checked = decimal.Parse( label58.Text ) <= gift;
            checkBox45.Checked = decimal.Parse( label59.Text ) <= gift;
            checkBox46.Checked = decimal.Parse( label60.Text ) <= gift;
            checkBox47.Checked = decimal.Parse( label61.Text ) <= gift;
            checkBox48.Checked = decimal.Parse( label62.Text ) <= gift;
            checkBox49.Checked = decimal.Parse( label63.Text ) <= gift;
            checkBox50.Checked = decimal.Parse( label64.Text ) <= gift;
            checkBox51.Checked = decimal.Parse( label65.Text ) <= gift;
            checkBox52.Checked = decimal.Parse( label66.Text ) <= gift;
            checkBox53.Checked = decimal.Parse( label67.Text ) <= gift;
            checkBox54.Checked = decimal.Parse( label68.Text ) <= gift;
            checkBox55.Checked = decimal.Parse( label69.Text ) <= gift;
            checkBox56.Checked = decimal.Parse( label70.Text ) <= gift;
            checkBox57.Checked = decimal.Parse( label71.Text ) <= gift;
            checkBox58.Checked = decimal.Parse( label72.Text ) <= gift;
            checkBox59.Checked = decimal.Parse( label73.Text ) <= gift;
            checkBox60.Checked = decimal.Parse( label74.Text ) <= gift;
            checkBox61.Checked = decimal.Parse( label75.Text ) <= gift;
            return;
        }
    }
}
